name: streamlit_env
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
  - snowflake
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - openpyxl
  - hdbscan
